### ISSUE TITLE
Current bug list

### ISSUE THREAD

**Issue by ele828** [NeuOL/neu-cn#8]
1. Favicon ->fixed
2. 网站地图  ->fixed
3. 兼容性 respond.js -> fixed
4. 首页和子页统一media query参数  ->fixed
   5.首页和子页 logo变形  -> fixed
5. 填写关于信息 
6. 专题banner图片变形问题
7. 冒烟测试

**Comment by ele828** [comment]
1. 高分辨率下 底部调节  ->fixed
2. 时间线li的宽度需要调整一下  ->fixed

**Comment by ele828** [comment]
- IE7，8下子页面排版混乱，估计是使用了不兼容的css属性 或 respond.js失效，而没有一个默认的布局？  -> fixed
- IE7下timeline错位，列表溢出，可以hack

**Comment by ele828** [comment]
All fixed!

**Comment by yfwz100** [comment]
:+1:
